import type { Product, Category } from "./types"

export const categories: Category[] = [
  { id: "all", name: "All Categories", icon: "🏪" },
  { id: "electronics", name: "Electronics", icon: "📱" },
  { id: "furniture", name: "Furniture", icon: "🪑" },
  { id: "clothing", name: "Clothing", icon: "👕" },
  { id: "books", name: "Books", icon: "📚" },
  { id: "sports", name: "Sports", icon: "⚽" },
  { id: "automotive", name: "Automotive", icon: "🚗" },
  { id: "home", name: "Home & Garden", icon: "🏡" },
  { id: "toys", name: "Toys & Games", icon: "🎮" },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "iPhone 14 Pro Max",
    description: "Excellent condition iPhone 14 Pro Max, 256GB, Space Black. Includes original box and charger.",
    price: 899,
    category: "electronics",
    condition: "like-new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "John Doe",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.8,
    },
    location: "San Francisco, CA",
    createdAt: "2024-01-15",
    featured: true,
    stock: 1,
  },
  {
    id: "2",
    title: "Modern Office Chair",
    description: "Ergonomic office chair with lumbar support. Perfect for home office setup.",
    price: 150,
    category: "furniture",
    condition: "good",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Sarah Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.9,
    },
    location: "New York, NY",
    createdAt: "2024-01-14",
    stock: 2,
  },
  {
    id: "3",
    title: "Vintage Leather Jacket",
    description: "Authentic vintage leather jacket, size M. Great for casual wear.",
    price: 75,
    category: "clothing",
    condition: "good",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Mike Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.6,
    },
    location: "Los Angeles, CA",
    createdAt: "2024-01-13",
    stock: 1,
  },
  {
    id: "4",
    title: 'MacBook Pro 16"',
    description: 'MacBook Pro 16" M2 chip, 512GB SSD, 16GB RAM. Perfect for professionals.',
    price: 1899,
    category: "electronics",
    condition: "like-new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Emily Chen",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 5.0,
    },
    location: "Seattle, WA",
    createdAt: "2024-01-12",
    featured: true,
    stock: 1,
  },
  {
    id: "5",
    title: "Gaming Setup - RTX 4080",
    description: "Complete gaming setup with RTX 4080, 32GB RAM, RGB lighting. Ready to game!",
    price: 2500,
    category: "electronics",
    condition: "new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Alex Turner",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.7,
    },
    location: "Austin, TX",
    createdAt: "2024-01-11",
    stock: 1,
  },
  {
    id: "6",
    title: "Dining Table Set",
    description: "Beautiful oak dining table with 6 chairs. Perfect for family dinners.",
    price: 450,
    category: "furniture",
    condition: "good",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Lisa Brown",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.9,
    },
    location: "Chicago, IL",
    createdAt: "2024-01-10",
    stock: 1,
  },
  {
    id: "7",
    title: "Designer Sneakers",
    description: "Limited edition designer sneakers, size 10. Worn only a few times.",
    price: 200,
    category: "clothing",
    condition: "like-new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "David Kim",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.5,
    },
    location: "Miami, FL",
    createdAt: "2024-01-09",
    stock: 1,
  },
  {
    id: "8",
    title: "Programming Books Collection",
    description: "Collection of 15 programming books including JavaScript, Python, and React.",
    price: 120,
    category: "books",
    condition: "good",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Rachel Green",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.8,
    },
    location: "Boston, MA",
    createdAt: "2024-01-08",
    stock: 1,
  },
  {
    id: "9",
    title: "Mountain Bike",
    description: "Trek mountain bike, 21-speed, excellent for trails and city riding.",
    price: 350,
    category: "sports",
    condition: "good",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Tom Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.6,
    },
    location: "Denver, CO",
    createdAt: "2024-01-07",
    stock: 1,
  },
  {
    id: "10",
    title: "Car Audio System",
    description: "Premium car audio system with subwoofer and amplifier. Professional installation available.",
    price: 800,
    category: "automotive",
    condition: "new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Carlos Rodriguez",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.9,
    },
    location: "Phoenix, AZ",
    createdAt: "2024-01-06",
    stock: 3,
  },
  {
    id: "11",
    title: "Garden Tool Set",
    description: "Complete garden tool set with shovel, rake, pruners, and more. Great for gardening enthusiasts.",
    price: 85,
    category: "home",
    condition: "like-new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Nancy Davis",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.7,
    },
    location: "Portland, OR",
    createdAt: "2024-01-05",
    stock: 2,
  },
  {
    id: "12",
    title: "PlayStation 5 Bundle",
    description: "PS5 console with 2 controllers and 5 games. Excellent condition, barely used.",
    price: 650,
    category: "toys",
    condition: "like-new",
    images: ["/placeholder.svg?height=300&width=300"],
    seller: {
      name: "Kevin Lee",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4.8,
    },
    location: "Las Vegas, NV",
    createdAt: "2024-01-04",
    featured: true,
    stock: 1,
  },
]
